### PR TITLE
Error handling

### LINKED ISSUE #986: Improve error message, if model can't be loaded
When starting [`fj-app`](https://github.com/hannobraun/Fornjot/tree/main/crates/fj-app), you tell it which model to load by passing a command-line argument (`-m`/`--model`). If that model can't be found, this results in an error message. This error message can be hard to understand, and lacks information that could help to make sense of the problem.

Here's the error message that this currently results in:
```
Error: Failed to load model: models/cuboid

Caused by:
    0: I/O error while loading model
    1: No such file or directory (os error 2)
```

There should be a lot more information here, to help the user determine *why* the model couldn't be loaded:

- In addition to the relative path shown here, also show the absolute path, in case that makes the error more obvious.
- Explain, step-by-step, how the path came to be:
  1. The current working directory.
  2. The [default path from the configuration](https://github.com/hannobraun/Fornjot/blob/67cc32db7cf4b757413ebebf075c8330c90fa723/crates/fj-app/src/config.rs#L12).
  3. The model passed via `-m`/`--model`, or the [default model from the configuration](https://github.com/hannobraun/Fornjot/blob/67cc32db7cf4b757413ebebf075c8330c90fa723/crates/fj-app/src/config.rs#L13) as a fallback.

This information should help users recognize what went wrong.

The code that builds the path and creates the error message is located in `fj-app`:
https://github.com/hannobraun/Fornjot/blob/67cc32db7cf4b757413ebebf075c8330c90fa723/crates/fj-app/src/main.rs#L49-L59

I'm labeling this as https://github.com/hannobraun/Fornjot/labels/good%20first%20issue, as this is a fairly isolated change that doesn't require a lot of knowledge about the context.

Also see #987, which is related.

### PR DESCRIPTION
**Pull request by ArshErgon**
for the issue #986 I have re-edited the error the Fornjot application.
Do review the PR

edit by @hannobraun:
Close #986 (to close the issue when this is merged)

### CODE REVIEW

**Review by hannobraun — CHANGES_REQUESTED** [review]
Thank you for the new pull request @ArshErgon! Unfortunately it still doesn't work. Here's what I get when running the Fornjot app from the repository root, without arguments:

```
$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/fj-app`
thread 'main' panicked at 'REASON', crates/fj-app/src/main.rs:49:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

We can't rely on the model being passed on the command line, as a default model can be specified in the configuration. This is why the code here looks at both the arguments and the configuration:
https://github.com/hannobraun/Fornjot/blob/8ece6e23c90b51495c192dd393372ae1b1910a8b/crates/fj-app/src/main.rs#L55

I think it should be possible to get the path for the error message from the `model_path` variable:
https://github.com/hannobraun/Fornjot/blob/8ece6e23c90b51495c192dd393372ae1b1910a8b/crates/fj-app/src/main.rs#L56-L57

**Comment by ArshErgon** [comment]
Hey @hannobraun well if I use `model_path` it will return as `model/testFile`, so this will it work for error message?

**Comment by hannobraun** [comment]
> if I use `model_path` it will return as `model/testFile`, so this will it work for error message?

Oh, wait, I think I said the wrong thing? The model name should be in the `model` variable, not `model_path`.

**Comment by ArshErgon** [comment]
okay, but can you tell me is anything in rust which can tell me attributes of a particular variable? like in python we have `print(dir(object))` or maybe you could recommend me some good VS code extension, at now I only have `rust-analyzer` its pretty hard for me to know what methods does a particular variable using

**Comment by hannobraun** [comment]
> okay, but can you tell me is anything in rust which can tell me attributes of a particular variable? like in python we have `print(dir(object))`

There's nothing in Rust that would let you print the methods that a type has, as far as I know. This makes sense, as Rust is a statically compiled language (unlike Python), so this kind of data is no longer available at runtime.

You can print actual data though, using [`dgb!`](https://doc.rust-lang.org/std/macro.dbg.html). There are other ways too, for example [`print!`](https://doc.rust-lang.org/std/macro.print.html)/[`println!`](https://doc.rust-lang.org/std/macro.println.html).


> or maybe you could recommend me some good VS code extension, at now I only have `rust-analyzer`

rust-analyzer is definitely the best Rust extension for VS code, but it's not well-suited to figure out which methods a type has. The best way to figure that out is to look at the documentation.


> its pretty hard for me to know what methods does a particular variable using

For types from the standard library, I recommend the [official documentation](https://doc.rust-lang.org/std/index.html). If you're using a type from a 3rd-part library, you can look up that library on [crates.io](https://crates.io/). Most have a link to documentation on the right. Most documentation is hosted on [docs.rs](https://docs.rs/), so you can also search there directly.

If you want to see the source code of a type, you can jump to it using rust-analyzer, using *Right Click* -> *Go to Definition*, or by pressing *F12* while the cursor is on top of the type name.

**Comment by ArshErgon** [comment]
@hannobraun is this you want? `cargo run` isn't panicking anymore

File: crates/fj-app/src/main.rs [hunk 1]
```diff
@@ -45,18 +45,28 @@ fn main() -> anyhow::Result<()> {
 
     let args = Args::parse();
     let config = Config::load()?;
-
+    // model name defined here.
+    let fetch_model_name =
+        (args.model.as_ref().or(config.default_model.as_ref()))
+            .unwrap()
```
Comment (hannobraun) [inline crates/fj-app/src/main.rs:51]: This breaks when no model is defined at all, so neither via a command-line argument, nor as a default model in the configuration. This is a case that is otherwise handled, see the [`if let` in line 62](https://github.com/hannobraun/Fornjot/blob/45abaf5feff821e311406789043133598221a1ed/crates/fj-app/src/main.rs#L62) and [its `else` in lines 96-98](https://github.com/hannobraun/Fornjot/blob/45abaf5feff821e311406789043133598221a1ed/crates/fj-app/src/main.rs#L96-L98).

This can be reproduced like this:
1. While in your branch, install `fj-app` by running this from the repository root: `cargo install --path crates/fj-app/`
2. Run this from any directory that has no Fornjot model, nor Fornjot configurat: `fj-app`

This results in the following error:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', crates/fj-app/src/main.rs:51:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Your code here duplicates the logic from line 62, which is a warning sign. Whenever you duplicate code like that, there's a danger that the two versions are different and one doesn't work correctly (as is the case here). Even if both work correctly, sooner or later one of the versions will be changed, and whoever does that might forget to update the other one.

The solution is to re-use the code that is already there. Instead of creating a new variable (`fetch_model_name`) here, why not move the code that formats the new error message into the `if let` (line 63 and following)? Then it can use the `model` variable that is already there.

**Review by hannobraun — CHANGES_REQUESTED** [review]
Thank you for keeping at it, @ArshErgon!

Unfortunately it now breaks in a different way. I've left a comment to explain that.

**Comment by ArshErgon** [comment]
@hannobraun I actually laughed when I read `it now breaks in different way` will see what I can do. thanks for guiding me so far.

File: crates/fj-app/src/main.rs [hunk 2]
```diff
@@ -45,18 +45,29 @@ fn main() -> anyhow::Result<()> {
...
+    let path_of_model = path.canonicalize().unwrap_or_default();
+
+    let model = if let Some(model) =
+        args.model.or(config.default_model).as_ref()
+    {
         let mut model_path = path;
         model_path.push(model);
         Some(Model::from_path(model_path.clone()).with_context(|| {
-            format!("Failed to load model: {}", model_path.display())
+            if path_of_model.as_os_str().is_empty() {
```
Comment (hannobraun) [inline crates/fj-app/src/main.rs:62]: Under which circumstances can `path_of_model` be empty? I suspect this can only happen, if `path.canonicalize()` above returns an `Err`.

If that is true, we can make things a bit more direct, doing something like this:

```
let abs_path = if let Ok(path_of_model) = path.canonicalize() {
    // insert error message using `path_of_model` here
} else {
    // insert error message that doesn't use `path_of_model` here
}
```

As a side note, this would be a prime use case [`let-else`](https://rust-lang.github.io/rfcs/3137-let-else.html). This feature isn't stable yet, but should become available soon.

File: crates/fj-app/src/main.rs [hunk 3]
```diff
@@ -45,18 +45,29 @@ fn main() -> anyhow::Result<()> {
...
+                format!(
+                    "Model is not defined, can't find model defined inside the default-model also, add model like \n cargo run -- -m {}", model.display()
+                )
```
Comment (hannobraun) [inline crates/fj-app/src/main.rs:65]: That error message could use some more detail. It doesn't say where it searched for the model, unlike the more detailed error message below.

File: crates/fj-app/src/main.rs [hunk 4]
```diff
@@ -45,18 +45,29 @@ fn main() -> anyhow::Result<()> {
...
+            } else {
+                format!(
+                "Failed to load model: {0}\ninside default models directory: '{1}'\nCan mainly caused by: \n1. Model '{2}' can not be found inside '{1}'\n2.'{2}' can be mis-typed see inside '{1}' for a match\n3. Define model is '{2}' couldn\'t be found ((defined in command-line arguments))", model_path.display(), path_of_model.display(), model.display()
+            )
```
Comment (hannobraun) [inline crates/fj-app/src/main.rs:69]: Having the error message in one long line like this can be a bit hard to read, so here's a tip on formatting strings: You can add a `\` to the end of a line, which will make the parser ignore everything until the next non-whitespace character. Using that trick, you can make it look like this:

```suggestion
                format!(
                    "Failed to load model: {0}\n\
                    inside default models directory: '{1}'\n\
                    Can mainly caused by: \n\
                    1. Model '{2}' can not be found inside '{1}'\n\
                    2.'{2}' can be mis-typed see inside '{1}' for a match\n\
                    3. Define model is '{2}' couldn\'t be found ((defined in command-line arguments))",
                    model_path.display(),
                    path_of_model.display(),
                    model.display()
            )
```

**Review by hannobraun — APPROVED** [review]
Thank you for the latest changes, @ArshErgon! Everything works great now, as far as I can tell. Thank you for keeping at it!

I've left some comments with suggestions, but this is fine as-is, and I'll be merging it now. Feel free to address these comments in a follow-up pull request, if you want to (or not, if you don't).

File: crates/fj-app/src/main.rs (hunk 2 above)
Comment (ArshErgon) [reply crates/fj-app/src/main.rs:62]: @hannobraun I will truly do another PR again,
I also tried to use that `if let` case but I was running it with `Some` and couldn't figure it out, and settle with using the simple `if else`.

File: crates/fj-app/src/main.rs (hunk 3 above)
Comment (ArshErgon) [reply crates/fj-app/src/main.rs:65]: sure will update it with something bit more reasonable.

File: crates/fj-app/src/main.rs (hunk 2 above)
Comment (hannobraun) [reply crates/fj-app/src/main.rs:62]: > I will truly do another PR again,

Thank you, that's great!

---

In case you're wondering how to figure out these kinds of things, here's where to find the necessary information in the standard library API reference:

If you check out the documentation, you can see that [`Path::canonicalize`](https://doc.rust-lang.org/std/path/struct.Path.html#method.canonicalize) returns a `Result` (specifically an [`io::Result`](https://doc.rust-lang.org/std/io/type.Result.html), which is defined in terms of [`result::Result`](https://doc.rust-lang.org/std/result/enum.Result.html)). `Result` has `Ok` and `Err` variants, which you can use with `if let` or `match`.

`Some`, on the other hand, is a variant of [`Option`](https://doc.rust-lang.org/std/option/enum.Option.html), which is *not* returned by `canonicalize`.
